Resolve "Add support to stylus".
picter/npm-package-boilerplate pull request #4
Opened 2017-08-16 13:19 UTC by gneutzling

2017-08-16 13:37 UTC, lcsrinaldi commented on .babelrc
> +  "presets": ["env", "react"]
Is this env preset helpful even without configuration (like target browser and environments)?

2017-08-16 13:37 UTC, lcsrinaldi commented
Just a single question. LGTM! :shipit:

2017-08-16 13:43 UTC, gneutzling commented on .babelrc
> +  "presets": ["env", "react"]
I followed the documentation https://github.com/babel/babel-preset-env#usage

But I am not sure if we should use other configs. We can improve that in the future, what do you think?

2017-08-16 13:50 UTC, noxan commented on .babelrc
> +  "presets": ["env", "react"]
If I remember correctly they deprecated a lot of the old presets in favor of the `env` preset. I like to see it here :)

2017-08-16 13:53 UTC, noxan requested changes

2017-08-16 13:53 UTC, noxan commented on webpack.config.js
> +    extensions: ['.js', '.jsx', '.svg'],
Should we really include `svg` here?

2017-08-16 13:53 UTC, noxan commented on webpack.config.js
> +        loaders: ['css-loader'],
Does css loader work without `style-loader`?

2017-08-16 13:53 UTC, noxan commented on webpack.config.js
> +        test: /\.svg/,
Does it lacks of a `$` ending character?

2017-08-16 13:53 UTC, noxan commented on webpack.config.js
> +        test: /\.css/,
Does it lacks of a `$` ending character?

2017-08-16 19:24 UTC, marcuscaum commented on webpack.config.js
> +      'process.env': {
Do we need this env variable?

2017-08-17 21:28 UTC, noxan approved these changes

2017-08-18 14:31 UTC, gneutzling commented on webpack.config.js
> +      'process.env': {
Actually we don't need that. Good catch, thanks!

2017-08-18 15:05 UTC, merged